#page title
page_title                                : Web AR                                        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1473085588                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://suwung-inc.github.io/puzzleAR/                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://drive.google.com/open?id=13_l3Z7Ylq64xNisq7tkyil3owdpZIfpX                                          # Enter Google Play Store URL.
presskit_download_link                    : https://suwung-inc.github.io                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Web AR Puzzle Game                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Freely Available - WTF License                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Web Augmented Reality Game Puzzle Of Skeleton.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Taufich Rizqi F                                
your_link                                 : https://suwung-inc.github.io                     
your_city                                 : South Korea                                
email_address                             : taufichrizqi@gmail.com
facebook_username                         :                                           
instagram_username                        : rizky_novaa
twitter_username                          : FTaufich
github_username                           : suwung-inc
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : No App Download
    description                           : I'm not writer. There goes my heart beating Cause you are the reason I'm losing my sleep Please come back now
    fontawesome_icon_name                 : magic
    
  - title                                 : iPhone Device Preview
    description                           : I'm not writer. I'd climb every mountain And swim every ocean Just to be with youAnd fix what I've broken Cause I need you to see That you are the reason
    fontawesome_icon_name                 : mobile

  - title                                 : Android Device Preview
    description                           : I'm not writer. There goes my mind racin And you are the reason That I'm still breathing I'm hopeless now
    fontawesome_icon_name                 : play-circle

  - title                                 : Desktop Preview
    description                           : I'm not writer. I'd climb every mountain And swim every ocean Just to be with you And fix what I've broken Oh, cause I need you to see That you are the reason
    fontawesome_icon_name                 : sync

  - title                                 : Support Any Web Browser
    description                           : I'm not writer. There goes my hands shaking And you are the reason My heart keeps bleeding I need you now
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : I'm not writer. The song was meant to be different at the beginning of writing process, telling the story of obstacles in love, but it transformed to be a beautiful ballad because love excels all of them after all.
    fontawesome_icon_name                 : star

  - title                                 : Fully Performance
    description                           : I'm not writer. If I could turn back the clock I'd make sure the light defeated the dark I'd spend every hour, of every day Keeping you safe
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Whatever
    description                           : I'm not writer. I'd climb every mountain And swim every ocean Just to be with you And fix what I've broken Oh, cause I need you to see That you are the reason
    fontawesome_icon_name                 : link

  - title                                 : Keep Calm
    description                           : I'm not writer. I don't wanna fight no more I don't wanna hide no more I don't wanna cry no more Come back I need you to hold me (You are the reason) Come a little closer now Just a little closer now Come a little closer I need you to hold me tonight
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
theme: jekyll-theme-cayman
